// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IGbxS_VHJImStrN7IRHFxpewedypPUA',
    appId: '1:36001346313:web:57a80e295917d213cbd9d8',
    messagingSenderId: '36001346313',
    projectId: 'midtermproject-ef3a2',
    authDomain: 'midtermproject-ef3a2.firebaseapp.com',
    storageBucket: 'midtermproject-ef3a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQPVWZ0QtI5O2Ax__r515M-RR9qx9g4TU',
    appId: '1:36001346313:android:a256f586a366cb89cbd9d8',
    messagingSenderId: '36001346313',
    projectId: 'midtermproject-ef3a2',
    storageBucket: 'midtermproject-ef3a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRoUxPP0Ts-gEYU-C4XOWlsiQum0IuCvU',
    appId: '1:36001346313:ios:99cfea635e277722cbd9d8',
    messagingSenderId: '36001346313',
    projectId: 'midtermproject-ef3a2',
    storageBucket: 'midtermproject-ef3a2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRoUxPP0Ts-gEYU-C4XOWlsiQum0IuCvU',
    appId: '1:36001346313:ios:99cfea635e277722cbd9d8',
    messagingSenderId: '36001346313',
    projectId: 'midtermproject-ef3a2',
    storageBucket: 'midtermproject-ef3a2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8IGbxS_VHJImStrN7IRHFxpewedypPUA',
    appId: '1:36001346313:web:4cfc2f5562ef141bcbd9d8',
    messagingSenderId: '36001346313',
    projectId: 'midtermproject-ef3a2',
    authDomain: 'midtermproject-ef3a2.firebaseapp.com',
    storageBucket: 'midtermproject-ef3a2.firebasestorage.app',
  );
}
